export const BASENAME = '/H4X0R.nws'
export const STORIES = '/'
export const JOBS = '/jobs'
export const ITEM = '/item/:id'
export const ABOUT = '/about'
export const ERROR = '/error'
export const NOT_FOUND = '/404'
